'--------------------------------------------------------------------------------
' Código gerado pela conversão de VB6 para VB.NET
' Code Generated by VB6 to VB.NET Conversion
'--------------------------------------------------------------------------------

' Código convertido do VB6 possui Option Strict Off por padrão
' VB6 converted code has Option Strict Off by default
Option Strict Off

Friend Class clsBuscaChaves

    Private lngReturn As Integer
    Private strReturnWinReg As String = ""

    ' CONVERSAO_INFO (#0551): O parâmetro 'strSoftware' não foi modificado ou passado para um método que o modifique. Considere remover o ByRef.
    Public Function BuscaVersao(ByRef strSoftware As String) As String

        ' Ler chave do Software / Versão
        ' Read Software key / Version
        lngReturn = objWinReg.QueryValueEx(HKEY_ENUM.HKEY_CLASSES_ROOT, strSoftware & ".Application\CurVer", "", 0, strReturnWinReg)

        If lngReturn Then
            Return strReturnWinReg
        Else
            ' Não possui o software Instalado
            ' You don't have the software installed
            Return "Não foi encontrada a chave do Aplicativo " & strSoftware & " neste equipamento." & vbCrLf &
                   "Application key not found for: " & strSoftware & " on this equipment."
        End If

    End Function

    '-------------------------------------------------------------------
    ' - API VIEWER -
    '-------------------------------------------------------------------
    ' C:\Program Files (x86)\Microsoft Visual Studio\COMMON\Tools\Winapi\WIN32API.TXT
    '-------------------------------------------------------------------
    ' API Type: Declares / Avaliable itens: "RegQueryValueEx"
    '-------------------------------------------------------------------
    'Public Declare Function RegQueryValueEx Lib "advapi32.dll"
    'Alias "RegQueryValueExA"
    '(ByVal hKey As Long, ByVal lpValueName As String, ByVal lpReserved As Long,
    ' lpType As Long, lpData As Any, lpcbData As Long)
    'As Long

    ' Note that if you declare the lpData parameter as String, you must pass it By Value.

#Region "Constructor"

    'A public default constructor
    Public Sub New()
        ' Add initialization code here
    End Sub

#End Region

End Class
