'--------------------------------------------------------------------------------
' Código gerado pela conversão de VB6 para VB.NET
' Code Generated by VB6 to VB.NET Conversion
'--------------------------------------------------------------------------------

' Código convertido do VB6 possui Option Strict Off por padrão
' VB6 converted code has Option Strict Off by default
Option Strict Off

Friend Module mdlPrincipal

    Public objWinReg As WinReg32
    Public objBuscaChaves As clsBuscaChaves

    ' Este construtor estatico serve para garantir a inicializacao da VBLibrary.
    ' This static constructor is used to guarantee the initialization of VBLibrary.
    Sub New()
        EnsureVB6LibraryInitialization()
    End Sub

    <STAThread()>
    Public Sub main()

        ' Henrique - Adicionei a seguinte linha manualmente
        ' Henrique - I added the following line manually
        Application.EnableVisualStyles()

        If objWinReg Is Nothing Then objWinReg = New WinReg32()

        If objBuscaChaves Is Nothing Then objBuscaChaves = New clsBuscaChaves()

        frmLerChaveOffice.Show()
    End Sub

End Module
