'--------------------------------------------------------------------------------
' Código gerado pela conversão de VB6 para VB.NET
' Code Generated by VB6 to VB.NET Conversion
'--------------------------------------------------------------------------------

' Código convertido do VB6 possui Option Strict Off por padrão
' VB6 converted code has Option Strict Off by default
Option Strict Off

Imports VB = Microsoft.VisualBasic

' Prover data types dos valores do banco de dados de registro do Windows.
' Provide data types of the values of the Windows registry database.
Public Enum REG_TYPE_ENUM
    REG_NONE = 0 ' No value type
    REG_SZ = 1 ' Unicode nul terminated string
    REG_EXPAND_SZ = 2 ' Unicode nul terminated string
    REG_BINARY = 3 ' Free form binary
    REG_DWORD = 4 ' 32-bit number
    REG_DWORD_BIG_ENDIAN = 5 ' 32-bit number
    REG_LINK = 6 ' Symbolic Link (unicode)
    REG_MULTI_SZ = 7 ' Multiple Unicode strings
End Enum

' Prover opções de criação de chaves no banco de dados de registro do Windows
' Provide key creation options in the Windows registry database.
Public Enum REG_OPTION_ENUM
    REG_OPTION_NON_VOLATILE = 0 ' Key is preserved when system is rebooted
    REG_OPTION_VOLATILE = 1 ' Key is not preserved when system is rebooted
End Enum

' Prover lista de valores indentificadores das chaves do banco de dados de registro do Windows.
' Provide list of values identifying the keys of the Windows registry database.
Public Enum HKEY_ENUM
    HKEY_CLASSES_ROOT = &H80000000
    HKEY_CURRENT_USER = &H80000001
    HKEY_LOCAL_MACHINE = &H80000002
    HKEY_USERS = &H80000003
    HKEY_CURRENT_CONFIG = &H80000005
    HKEY_DYN_DATA = &H80000006
End Enum

Friend Class WinReg32

    '--------------------------------------------------------------------------------
    ' Nome            : WinReg32.cls
    ' Descrição       : Classe utilitária de manipulação do banco de dados de registro do Windows
    '                   Utility class for manipulating the Windows registry database
    ' Autor           :
    ' Início          : 21/03/1999
    ' Ultima Alteração: 10/08/2001
    ' Dependencias    :
    '--------------------------------------------------------------------------------

    ' Fechar uma chave previamente aberta no banco de dados de registro do Windows.
    ' Close a previously opened key in the Windows registry database.
    ' CONVERSAO_INFO (#0531): Você pode substituir as chamadas à rotina 'RegCloseKey' pelo(s) seguinte(s) método(s) .NET: Microsoft.Win32.RegistryKey.Close.
    ' CONVERSAO_INFO (#0531): You can replace the calls to the 'RegCloseKey' routine with the following .NET method(s): Microsoft.Win32.RegistryKey.Close.
    Private Declare Function RegCloseKey Lib "advapi32.dll" (hKey As Integer) As Integer

    ' Criar uma chave no banco de dados de registro do Windows. Se a chave já existir, o método irá abri-la.
    ' Create a key in the Windows registry database. If the key already exists, the method will open it.
    ' CONVERSAO_INFO (#0531): Você pode substituir as chamadas à rotina 'RegCreateKeyEx' pelo(s) seguinte(s) método(s) .NET: Microsoft.Win32.RegistryKey.CreateSubKey.
    ' CONVERSAO_INFO (#0531): You can replace the calls to the 'RegCloseKey' routine with the following .NET method(s): Microsoft.Win32.RegistryKey.Close.
    ' CONVERSAO_INFO (#0511): O membro 'RegCreateKeyEx' é referenciado apenas por membros que não são usados nessa aplicação.
    ' CONVERSAO_INFO (#0511): The member 'RegCreateKeyEx' is referenced only by members that are not used in this application.
    Private Declare Function RegCreateKeyEx Lib "advapi32.dll" Alias "RegCreateKeyExA" (hKey As Integer, lpSubKey As String, Reserved As Integer, lpClass As String, dwOptions As Integer, samDesired As Integer, ByRef lpSecurityAttributes As WinReg32.SECURITY_ATTRIBUTES, ByRef phkResult As Integer, ByRef lpdwDisposition As Integer) As Integer

    ' Conectar ao banco de dados de registro do Windows de uma máquina remota.
    ' Connect to the Windows registry database of a remote machine.
    ' CONVERSAO_INFO (#0531): Você pode substituir as chamadas à rotina 'RegConnectRegistry' pelo(s) seguinte(s) método(s) .NET: Microsoft.Win32.RegistryKey.OpenRemoteBaseKey.
    ' CONVERSAO_INFO (#0531): You can replace the calls to the 'RegCloseKey' routine with the following .NET method(s): Microsoft.Win32.RegistryKey.Close.
    Private Declare Function RegConnectRegistry Lib "advapi32.dll" Alias "RegConnectRegistryA" (lpMachineName As String, hKey As Integer, ByRef phkResult As Integer) As Integer

    ' Deletar uma chave do banco de dados de registro do Windows.
    ' Delete a key from the Windows registry database.
    ' CONVERSAO_INFO (#0531): Você pode substituir as chamadas à rotina 'RegDeleteKey' pelo(s) seguinte(s) método(s) .NET: Microsoft.Win32.RegistryKey.DeleteSubKeyTree.
    ' CONVERSAO_INFO (#0531): You can replace the calls to the 'RegCloseKey' routine with the following .NET method(s): Microsoft.Win32.RegistryKey.Close.
    ' CONVERSAO_INFO (#0511): O membro 'RegDeleteKey' é referenciado apenas por membros que não são usados nessa aplicação.
    ' CONVERSAO_INFO (#0511): The member 'RegCreateKeyEx' is referenced only by members that are not used in this application.
    Private Declare Function RegDeleteKey Lib "advapi32.dll" Alias "RegDeleteKeyA" (hKey As Integer, lpSubKey As String) As Integer

    ' Remover uma valor do banco de dados de registro do Windows.
    ' Remove a value from the Windows registry database.
    ' CONVERSAO_INFO (#0531): Você pode substituir as chamadas à rotina 'RegDeleteValue' pelo(s) seguinte(s) método(s) .NET: Microsoft.Win32.RegistryKey.DeleteValue.
    ' CONVERSAO_INFO (#0531): You can replace the calls to the 'RegCloseKey' routine with the following .NET method(s): Microsoft.Win32.RegistryKey.Close.
    ' CONVERSAO_INFO (#0511): O membro 'RegDeleteValue' é referenciado apenas por membros que não são usados nessa aplicação.
    ' CONVERSAO_INFO (#0511): The member 'RegCreateKeyEx' is referenced only by members that are not used in this application.
    Private Declare Function RegDeleteValue Lib "advapi32.dll" Alias "RegDeleteValueA" (hKey As Integer, lpValueName As String) As Integer

    ' Abrir uma chave no banco de dados de registro do Windows.
    ' CONVERSAO_INFO (#0531): Você pode substituir as chamadas à rotina 'RegOpenKeyEx' pelo(s) seguinte(s) método(s) .NET: Microsoft.Win32.RegistryKey.OpenSubKey.
    ' CONVERSAO_INFO (#0531): You can replace the calls to the 'RegCloseKey' routine with the following .NET method(s): Microsoft.Win32.RegistryKey.Close.
    Private Declare Function RegOpenKeyEx Lib "advapi32.dll" Alias "RegOpenKeyExA" (hKey As Integer, lpSubKey As String, ulOptions As Integer, samDesired As Integer, ByRef phkResult As Integer) As Integer

    ' Ler um valor no banco de dados de registro do Windows.
    ' Note que se você declarar o parâmetro lpData como String,
    ' você precisa passa-lo por valor.
    ' CONVERSAO_INFO (#0531): Você pode substituir as chamadas à rotina 'RegQueryValueEx' pelo(s) seguinte(s) método(s) .NET: Microsoft.Win32.RegistryKey.GetValue.
    ' CONVERSAO_INFO (#0531): You can replace the calls to the 'RegCloseKey' routine with the following .NET method(s): Microsoft.Win32.RegistryKey.Close.
    Private Declare Function RegQueryValueEx Lib "advapi32.dll" Alias "RegQueryValueExA" (hKey As Integer, lpValueName As String, lpReserved As Integer, ByRef lpType As Integer, lpData As String, ByRef lpcbData As Integer) As Integer

    ' Gravar um valor no banco de dados de registro do Windows.
    ' Note que se você declarar o parâmetro lpData como String,
    ' você precisa passa-lo por valor.
    ' CONVERSAO_INFO (#0531): Você pode substituir as chamadas à rotina 'RegSetValueEx' pelo(s) seguinte(s) método(s) .NET: Microsoft.Win32.RegistryKey.SetValue.
    ' CONVERSAO_INFO (#0531): You can replace the calls to the 'RegCloseKey' routine with the following .NET method(s): Microsoft.Win32.RegistryKey.Close.
    ' CONVERSAO_INFO (#0511): O membro 'RegSetValueEx' é referenciado apenas por membros que não são usados nessa aplicação.
    ' CONVERSAO_INFO (#0511): The member 'RegCreateKeyEx' is referenced only by members that are not used in this application.
    Private Declare Function RegSetValueEx Lib "advapi32.dll" Alias "RegSetValueExA" (hKey As Integer, lpValueName As String, Reserved As Integer, dwType As Integer, lpData As String, cbData As Integer) As Integer

    ' Prover permissões para as chaves do banco de dados de registro do Windows.
    ' Provide permissions to the Windows registry database keys.
    ' CONVERSAO_INFO (#0561): O símbolo 'KEY_CREATE_LINK' foi definido sem o uso explícito da cláusula "As".
    ' CONVERSAO_INFO (#0561): The 'KEY_CREATE_LINK' symbol was defined without the explicit use of the 'As' clause.
    Private Const KEY_CREATE_LINK As Short = &H20S

    ' CONVERSAO_INFO (#0561): O símbolo 'KEY_CREATE_SUB_KEY' foi definido sem o uso explícito da cláusula "As".
    ' CONVERSAO_INFO (#0561): The 'KEY_CREATE_LINK' symbol was defined without the explicit use of the 'As' clause.
    Private Const KEY_CREATE_SUB_KEY As Short = &H4S

    ' CONVERSAO_INFO (#0561): O símbolo 'KEY_ENUMERATE_SUB_KEYS' foi definido sem o uso explícito da cláusula "As".
    ' CONVERSAO_INFO (#0561): The 'KEY_CREATE_LINK' symbol was defined without the explicit use of the 'As' clause.
    Private Const KEY_ENUMERATE_SUB_KEYS As Short = &H8S

    ' CONVERSAO_INFO (#0561): O símbolo 'READ_CONTROL' foi definido sem o uso explícito da cláusula "As".
    ' CONVERSAO_INFO (#0561): The 'KEY_CREATE_LINK' symbol was defined without the explicit use of the 'As' clause.
    Private Const READ_CONTROL As Integer = &H20000I

    ' CONVERSAO_INFO (#0561): O símbolo 'STANDARD_RIGHTS_READ' foi definido sem o uso explícito da cláusula "As".
    ' CONVERSAO_INFO (#0561): The 'KEY_CREATE_LINK' symbol was defined without the explicit use of the 'As' clause.
    Private Const STANDARD_RIGHTS_READ As Integer = (READ_CONTROL)

    ' CONVERSAO_INFO (#0561): O símbolo 'SYNCHRONIZE' foi definido sem o uso explícito da cláusula "As".
    ' CONVERSAO_INFO (#0561): The 'KEY_CREATE_LINK' symbol was defined without the explicit use of the 'As' clause.
    Private Const SYNCHRONIZE As Integer = &H100000I

    ' CONVERSAO_INFO (#0561): O símbolo 'KEY_NOTIFY' foi definido sem o uso explícito da cláusula "As".
    ' CONVERSAO_INFO (#0561): The 'KEY_CREATE_LINK' symbol was defined without the explicit use of the 'As' clause.
    Private Const KEY_NOTIFY As Short = &H10S

    ' CONVERSAO_INFO (#0561): O símbolo 'KEY_QUERY_VALUE' foi definido sem o uso explícito da cláusula "As".
    ' CONVERSAO_INFO (#0561): The 'KEY_CREATE_LINK' symbol was defined without the explicit use of the 'As' clause.
    Private Const KEY_QUERY_VALUE As Short = &H1S

    ' CONVERSAO_INFO (#0561): O símbolo 'KEY_SET_VALUE' foi definido sem o uso explícito da cláusula "As".
    ' CONVERSAO_INFO (#0561): The 'KEY_CREATE_LINK' symbol was defined without the explicit use of the 'As' clause.
    Private Const KEY_SET_VALUE As Short = &H2S

    ' CONVERSAO_INFO (#0561): O símbolo 'KEY_READ' foi definido sem o uso explícito da cláusula "As".
    ' CONVERSAO_INFO (#0561): The 'KEY_CREATE_LINK' symbol was defined without the explicit use of the 'As' clause.
    Private Const KEY_READ As Integer = ((STANDARD_RIGHTS_READ Or KEY_QUERY_VALUE Or KEY_ENUMERATE_SUB_KEYS Or KEY_NOTIFY) And (Not SYNCHRONIZE))

    ' CONVERSAO_INFO (#0501): O membro 'KEY_EXECUTE' não é usada em nenhum lugar nessa aplicação.
    ' CONVERSAO_INFO (#0501): The 'KEY_WRITE' member is not used anywhere in this application.
    Private Const KEY_EXECUTE As Integer = ((KEY_READ) And (Not SYNCHRONIZE))

    ' CONVERSAO_INFO (#0561): O símbolo 'STANDARD_RIGHTS_ALL' foi definido sem o uso explícito da cláusula "As".
    ' CONVERSAO_INFO (#0561): The 'KEY_CREATE_LINK' symbol was defined without the explicit use of the 'As' clause.
    Private Const STANDARD_RIGHTS_ALL As Integer = &H1F0000I

    ' CONVERSAO_INFO (#0511): O membro 'KEY_ALL_ACCESS' é referenciado apenas por membros que não são usados nessa aplicação.
    ' CONVERSAO_INFO (#0561): O símbolo 'KEY_ALL_ACCESS' foi definido sem o uso explícito da cláusula "As".
    Private Const KEY_ALL_ACCESS As Integer = ((STANDARD_RIGHTS_ALL Or KEY_QUERY_VALUE Or KEY_SET_VALUE Or KEY_CREATE_SUB_KEY Or KEY_ENUMERATE_SUB_KEYS Or KEY_NOTIFY Or KEY_CREATE_LINK) And (Not SYNCHRONIZE))

    ' CONVERSAO_INFO (#0561): O símbolo 'STANDARD_RIGHTS_WRITE' foi definido sem o uso explícito da cláusula "As".
    ' CONVERSAO_INFO (#0561): The 'KEY_CREATE_LINK' symbol was defined without the explicit use of the 'As' clause.
    Private Const STANDARD_RIGHTS_WRITE As Integer = (READ_CONTROL)

    ' CONVERSAO_INFO (#0501): O membro 'KEY_WRITE' não é usada em nenhum lugar nessa aplicação.
    ' CONVERSAO_INFO (#0501): The 'KEY_WRITE' member is not used anywhere in this application.
    Private Const KEY_WRITE As Integer = ((STANDARD_RIGHTS_WRITE Or KEY_SET_VALUE Or KEY_CREATE_SUB_KEY) And (Not SYNCHRONIZE))

    ' Prover informação se um chave foi criada ou aberta pela
    ' chamada a API RegCreateKeyEx.
    ' CONVERSAO_INFO (#0511): O membro 'REG_CREATED_NEW_KEY' é referenciado apenas por membros que não são usados nessa aplicação.
    ' CONVERSAO_INFO (#0511): The member 'REG_CREATED_NEW_KEY' is referenced only by members that are not used in this application.
    ' CONVERSAO_INFO (#0561): O símbolo 'REG_CREATED_NEW_KEY' foi definido sem o uso explícito da cláusula "As".
    ' CONVERSAO_INFO (#0561): The 'KEY_CREATE_LINK' symbol was defined without the explicit use of the 'As' clause.
    Private Const REG_CREATED_NEW_KEY As Short = &H1S

    ' New Registry Key created
    ' CONVERSAO_INFO (#0511): O membro 'REG_OPENED_EXISTING_KEY' é referenciado apenas por membros que não são usados nessa aplicação.
    ' CONVERSAO_INFO (#0511): The member 'REG_CREATED_NEW_KEY' is referenced only by members that are not used in this application.
    ' CONVERSAO_INFO (#0561): O símbolo 'REG_OPENED_EXISTING_KEY' foi definido sem o uso explícito da cláusula "As".
    ' CONVERSAO_INFO (#0561): The 'KEY_CREATE_LINK' symbol was defined without the explicit use of the 'As' clause.
    Private Const REG_OPENED_EXISTING_KEY As Short = &H2S

    ' Existing Key opened

    ' Tipo definido para atributos de segurança.
    ' CONVERSAO_INFO (#0511): O membro 'SECURITY_ATTRIBUTES' é referenciado apenas por membros que não são usados nessa aplicação.
    ' CONVERSAO_INFO (#0511): The member 'REG_CREATED_NEW_KEY' is referenced only by members that are not used in this application.
    Friend Structure SECURITY_ATTRIBUTES

        Public nLength As Integer
        Public lpSecurityDescriptor As Integer
        Public bInheritHandle As Integer
    End Structure

    ' CONVERSAO_INFO (#0501): O membro 'CreateKeyEx' não é usada em nenhum lugar nessa aplicação.
    ' CONVERSAO_INFO (#0501): The' CreateKeyEx 'member is not used anywhere in this application.
    ' CONVERSAO_INFO (#0551): O parâmetro 'lpMachineName' não foi modificado ou passado para um método que o modifique. Considere remover o ByRef.
    ' CONVERSAO_INFO (#0551): The 'lpMachineName' parameter has not been modified or passed to a method that modifies it. Consider removing ByRef.
    Public Function CreateKeyEx(hKey As HKEY_ENUM, lpSubKey As String, lpClass As String, dwOptions As REG_OPTION_ENUM, ByRef phkResult As Integer, ByRef lpdwDisposition As Integer, ByRef lpDispDescription As String, Optional ByRef lpMachineName As Object = MissingValue6) As Integer
        ' CONVERSAO_INFO (#03C1): A próxima instrução é válida para parâmetros opcionais que são empty, null, ou missing.
        ' CONVERSAO_INFO (#03C1): The next statement is valid for optional parameters that are empty, null, or missing.
        FixOptionalParameter6(lpMachineName)

        ' Área para declaração de variáveis e objetos de escopo local.
        ' Area for declaration of variables and objects of local scope.
        Dim lngReturn As Integer
        Dim lpSecurityAttributes As WinReg32.SECURITY_ATTRIBUTES

        On Error GoTo ErrorHandler

        ' Avaliar se o parâmetro lpMachineName foi informado.
        ' Evaluate whether the lpMachineName parameter has been reported.
        If Not IsMissing6(lpMachineName) Then

            ' Ativar API para conectar-se a um banco de dados de registro do Windows de uma máquina remota.
            ' Enable API to connect to a Windows registry database from a remote machine.
            ' CONVERSAO_AVISO (#0354): Não é possível ler o membro padrão de 'lpMachineName'. Considere utilizar a rotina GetDefaultMember6.
            ' CONVERSAO_AVISO (#0354): Unable to read the default member of' lpMachineName '. Consider using the GetDefaultMember6 routine.
            lngReturn = RegConnectRegistry(CStr(lpMachineName), hKey, phkResult)

            ' Avaliar se a API retornou sucesso.
            ' Evaluate whether the API has returned success.
            If lngReturn <> 0 Then
                GoTo ErrorHandler
            End If

            ' Atribuir o handler para a chave do registro remoto ao parâmetro hKey.
            ' Assign the handler for the remote registry key to the hKey parameter.
            hKey = phkResult

        End If

        ' Ativar API para ler o valor.
        ' Enable API to read the value.
        lngReturn = RegCreateKeyEx(hKey, lpSubKey, 0%, lpClass, dwOptions, KEY_ALL_ACCESS, lpSecurityAttributes, phkResult, lpdwDisposition)

        ' Avaliar se a API retornou sucesso.
        ' Evaluate whether the API has returned success.
        If lngReturn <> 0 Then
            GoTo ErrorHandler
        End If

        ' Avalair se a chave foi criada ou aberta.
        ' Evaluate whether the key was created or opened.
        If lpdwDisposition = REG_CREATED_NEW_KEY Then
            lpDispDescription = "The key did not exist and was created."
        ElseIf lpdwDisposition = REG_OPENED_EXISTING_KEY Then
            lpDispDescription = "The key existed and was simply opened without being changed."
        End If

        ' Fechar a chave no banco de dados de registro do Windows.
        ' Close the key in the Windows registry database.
        RegCloseKey((hKey))

        ' Retornar sucesso ao método.
        ' Return success to method.
        Return -1

ErrorHandler:

        ' Fechar a chave no banco de dados de registro do Windows.
        ' Close the key in the Windows registry database.
        RegCloseKey((phkResult))

        ' Retornar código de erro ao método.
        ' Return error code to method.
        Return 0

    End Function

    ' CONVERSAO_INFO (#0501): O membro 'DeleteKey' não é usada em nenhum lugar nessa aplicação.
    ' CONVERSAO_INFO (#0501): The' CreateKeyEx 'member is not used anywhere in this application.
    ' CONVERSAO_INFO (#0551): O parâmetro 'lpMachineName' não foi modificado ou passado para um método que o modifique. Considere remover o ByRef.
    ' CONVERSAO_INFO (#0551): The 'lpMachineName' parameter has not been modified or passed to a method that modifies it. Consider removing ByRef.
    Public Function DeleteKey(hKey As HKEY_ENUM, lpSubKey As String, Optional ByRef lpMachineName As Object = MissingValue6) As Integer
        ' CONVERSAO_INFO (#03C1): A próxima instrução é válida para parâmetros opcionais que são empty, null, ou missing.
        ' CONVERSAO_INFO (#03C1): The next statement is valid for optional parameters that are empty, null, or missing.
        FixOptionalParameter6(lpMachineName)

        ' Área para declaração de variáveis e objetos de escopo local.
        ' Area for declaration of variables and objects of local scope.
        Dim lngReturn As Integer
        Dim phkResult As Integer

        On Error GoTo ErrorHandler

        ' Avaliar se o parâmetro lpMachineName foi informado.
        ' Evaluate whether the lpMachineName parameter has been reported.
        If Not IsMissing6(lpMachineName) Then

            ' Ativar API para conectar-se a um banco de dados de registro do Windows de uma máquina remota.
            ' Enable API to connect to a Windows registry database from a remote machine.
            ' CONVERSAO_AVISO (#0354): Não é possível ler o membro padrão de 'lpMachineName'. Considere utilizar a rotina GetDefaultMember.
            ' CONVERSAO_AVISO (#0354): Unable to read the default member of 'lpMachineName'. Consider using the GetDefaultMember routine.
            lngReturn = RegConnectRegistry(CStr(lpMachineName), hKey, phkResult)

            ' Avaliar se a API retornou sucesso.
            ' Evaluate whether the API has returned success.
            If lngReturn <> 0 Then
                GoTo ErrorHandler
            End If

            ' Atribuir o handler para a chave do registro remoto ao parâmetro hKey.
            ' Assign the handler for the remote registry key to the hKey parameter.
            hKey = phkResult

        End If

        ' Ativar API para deletar uma chave do banco de dados de registro do Windows.
        ' Enable API to delete a key from the Windows registry database.
        lngReturn = RegDeleteKey(hKey, lpSubKey)

        ' Avaliar se a API retornou sucesso.
        ' Evaluate whether the API has returned success.
        If lngReturn <> 0 Then
            GoTo ErrorHandler
        End If

        ' Fechar a chave no banco de dados de registro do Windows.
        ' Close the key in the Windows registry database.
        RegCloseKey((hKey))

        ' Retornar sucesso ao método.
        ' Return success to method.
        Return -1

ErrorHandler:

        ' Fechar a chave no banco de dados de registro do Windows.
        ' Close the key in the Windows registry database.
        RegCloseKey((phkResult))

        ' Retornar código de erro ao método.
        ' Return error code to method.
        Return 0

    End Function

    ' CONVERSAO_INFO (#0501): O membro 'DeleteValue' não é usada em nenhum lugar nessa aplicação.
    ' CONVERSAO_INFO (#0501): The 'KEY_WRITE' member is not used anywhere in this application.
    ' CONVERSAO_INFO (#0551): O parâmetro 'lpMachineName' não foi modificado ou passado para um método que o modifique. Considere remover o ByRef.
    ' CONVERSAO_INFO (#0551): The 'lpMachineName' parameter has not been modified or passed to a method that modifies it. Consider removing ByRef.
    Public Function DeleteValue(hKey As HKEY_ENUM, lpSubKey As String, lpValueName As String, Optional ByRef lpMachineName As Object = MissingValue6) As Integer
        ' CONVERSAO_INFO (#03C1): A próxima instrução é válida para parâmetros opcionais que são empty, null, ou missing.
        ' CONVERSAO_INFO (#03C1): The next statement is valid for optional parameters that are empty, null, or missing.
        FixOptionalParameter6(lpMachineName)

        ' Área para declaração de variáveis e objetos de escopo local.
        ' Area for declaration of variables and objects of local scope.
        Dim lngReturn As Integer
        Dim phkResult As Integer

        On Error GoTo ErrorHandler

        ' Abrir a chave no banco de dados de registro do Windows.
        ' Open the key in the Windows registry database.
        lngReturn = OpenKeyEx(hKey, lpSubKey, phkResult, KEY_ALL_ACCESS, lpMachineName)

        ' Avaliar se a API retornou sucesso.
        If lngReturn <> 0 Then
            GoTo ErrorHandler
        End If

        ' Ativar API para deletar um valor do banco de dados de registro do Windows.
        ' Enable API to delete a value from the Windows registry database.
        lngReturn = RegDeleteValue(phkResult, lpValueName)

        ' Avaliar se a API retornou sucesso.
        ' Evaluate whether the API has returned success.
        If lngReturn <> 0 Then
            GoTo ErrorHandler
        End If

        ' Fechar a chave no banco de dados de registro do Windows.
        ' Close the key in the Windows registry database.
        RegCloseKey((phkResult))

        ' Retornar sucesso ao método.
        ' Return success to method.
        Return -1

ErrorHandler:

        ' Fechar a chave no banco de dados de registro do Windows.
        ' Close the key in the Windows registry database.
        RegCloseKey((phkResult))

        ' Retornar código de erro ao método.
        ' Return error code to method.
        Return 0

    End Function

    ' CONVERSAO_INFO (#0551): O parâmetro 'lpMachineName' não foi modificado ou passado para um método que o modifique. Considere remover o ByRef.
    ' CONVERSAO_INFO (#0551): The 'lMachineName' parameter has not been modified or passed to a method that modifies it. Consider removing ByRef.
    Private Function OpenKeyEx(hKey As Integer, lpSubKey As String, ByRef phkResult As Integer, samDesired As Integer, Optional ByRef lpMachineName As Object = MissingValue6) As Integer
        ' CONVERSAO_INFO (#03C1): A próxima instrução é válida para parâmetros opcionais que são empty, null, ou missing.
        ' CONVERSAO_INFO (#03C1): The next statement is valid for optional parameters that are empty, null, or missing.
        FixOptionalParameter6(lpMachineName)

        ' Área para declaração de variáveis e objetos de escopo local.
        ' Area for declaration of variables and objects of local scope.
        Dim lngReturn As Integer

        On Error GoTo ErrorHandler

        ' Avaliar se o parâmetro lpMachineName foi informado.
        ' Evaluate whether the lpMachineName parameter has been reported.
        If Not IsMissing6(lpMachineName) Then

            ' Ativar API para conectar-se a um banco de dados de registro do Windows de uma máquina remota.
            ' Enable API to connect to a Windows registry database from a remote machine.
            ' CONVERSAO_AVISO (#0354): Não é possível ler o membro padrão de 'lpMachineName'. Considere utilizar a rotina GetDefaultMember.
            ' CONVERSAO_AVISO (#0354): Unable to read the default member of' lpMachineName '. Consider using the GetDefaultMember routine.
            lngReturn = RegConnectRegistry(CStr(lpMachineName), hKey, phkResult)

            ' Avaliar se a API retornou sucesso.
            ' Evaluate whether the API has returned success.
            If lngReturn <> 0 Then
                GoTo ErrorHandler
            End If

            ' Atribuir o handler para a chave do registro remoto ao parâmetro hKey.
            ' Assign the handler for the remote registry key to the hKey parameter.
            hKey = phkResult

        End If

        ' Ativar API para abrir a chave no banco de dados de registro do Windows.
        ' Enable API to open the key in the Windows registry database.
        lngReturn = RegOpenKeyEx(hKey, lpSubKey, 0%, samDesired, phkResult)

        ' Avaliar se a API retornou sucesso.
        ' Evaluate whether the API has returned success.
        If lngReturn <> 0 Then
            GoTo ErrorHandler
        End If

        ' Retornar sucesso ao método.
        ' Return success to method.
        Return 0

ErrorHandler:

        ' Retornar código de erro ao método.
        ' Return error code to method.
        Return lngReturn

    End Function

    ' CONVERSAO_INFO (#0551): O parâmetro 'lpMachineName' não foi modificado ou passado para um método que o modifique. Considere remover o ByRef.
    ' CONVERSAO_INFO (#0551): The 'lpMachineName' parameter has not been modified or passed to a method that modifies it. Consider removing ByRef.
    Public Function QueryValueEx(hKey As HKEY_ENUM, lpSubKey As String, lpValueName As String, ByRef lpType As Integer, ByRef lpData As String, Optional ByRef lpMachineName As Object = MissingValue6) As Integer
        ' CONVERSAO_INFO (#03C1): A próxima instrução é válida para parâmetros opcionais que são empty, null, ou missing.
        ' CONVERSAO_INFO (#03C1): The next statement is valid for optional parameters that are empty, null, or missing.
        FixOptionalParameter6(lpMachineName)

        ' Área para declaração de variáveis e objetos de escopo local.
        ' Area for declaration of variables and objects of local scope.
        Dim lngReturn As Integer
        Dim phkResult As Integer
        Dim lpDataTmp As New VB6FixedString(255)
        Dim lpchData As Integer

        On Error GoTo ErrorHandler

        ' Inicializar Buffer.
        ' Initialize Buffer.
        lpchData = 255

        ' Abrir a chave no banco de dados de registro do Windows.
        ' Open the key in the Windows registry database.
        lngReturn = OpenKeyEx(hKey, lpSubKey, phkResult, KEY_READ, lpMachineName)

        ' Avaliar se a API retornou sucesso.
        ' Evaluate whether the API has returned success.
        If lngReturn <> 0 Then
            GoTo ErrorHandler
        End If

        ' Ativar API para ler o valor.
        ' Enable API to read the value.
        lngReturn = RegQueryValueEx(phkResult, lpValueName, 0%, lpType, lpDataTmp.Value, lpchData)

        ' Avaliar se a API retornou sucesso.
        ' Evaluate whether the API has returned success.
        If lngReturn <> 0 Then
            GoTo ErrorHandler
        End If

        ' Avaliar qual o data type do valor que foi lido do banco de dados de registro do Windows.
        ' Evaluate the data type of the value that was read from the Windows registry database.
        If lpType = REG_TYPE_ENUM.REG_SZ Or lpType = REG_TYPE_ENUM.REG_EXPAND_SZ Or lpType = REG_TYPE_ENUM.REG_MULTI_SZ Then
            ' Valor possui null terminate.
            ' Value has null terminate.
            lpData = VB.Left(lpDataTmp.Value, lpchData - 1)
        Else
            lpData = VB.Left(lpDataTmp.Value, lpchData)
        End If

        ' Fechar a chave no banco de dados de registro do Windows.
        ' Close the key in the Windows registry database.
        RegCloseKey((phkResult))

        ' Retornar sucesso ao método.
        ' Return success to method.
        Return -1

ErrorHandler:

        ' Fechar a chave no banco de dados de registro do Windows.
        ' Close the key in the Windows registry database.
        RegCloseKey((phkResult))

        ' Retornar código de erro ao método.
        ' Return error code to method.
        Return 0

    End Function

    ' CONVERSAO_INFO (#0501): O membro 'SetValueEx' não é usada em nenhum lugar nessa aplicação.
    ' CONVERSAO_INFO (#0501): The 'KEY_WRITE' member is not used anywhere in this application.
    ' CONVERSAO_INFO (#0551): O parâmetro 'lpMachineName' não foi modificado ou passado para um método que o modifique. Considere remover o ByRef.
    ' CONVERSAO_INFO (#0551): The 'lpMachineName' parameter has not been modified or passed to a method that modifies it. Consider removing ByRef.
    Public Function SetValueEx(hKey As HKEY_ENUM, lpSubKey As String, lpValueName As String, dwType As REG_TYPE_ENUM, lpData As String, Optional ByRef lpMachineName As Object = MissingValue6) As Integer
        ' CONVERSAO_INFO (#03C1): A próxima instrução é válida para parâmetros opcionais que são empty, null, ou missing.
        ' CONVERSAO_INFO (#03C1): The next statement is valid for optional parameters that are empty, null, or missing.
        FixOptionalParameter6(lpMachineName)

        ' Área para declaração de variáveis e objetos de escopo local.
        ' Area for declaration of variables and objects of local scope.
        Dim lngReturn As Integer
        Dim phkResult As Integer

        On Error GoTo ErrorHandler

        ' Abrir a chave no banco de dados de registro do Windows.
        ' Open the key in the Windows registry database.
        lngReturn = OpenKeyEx(hKey, lpSubKey, phkResult, KEY_ALL_ACCESS, lpMachineName)

        ' Avaliar se a API retornou sucesso.
        ' Evaluate whether the API has returned success.
        If lngReturn <> 0 Then
            GoTo ErrorHandler
        End If

        ' Ativar API para gravar o valor no banco de dados de registro do Windows.
        ' Enable API to write the value to the Windows registry database.
        lngReturn = RegSetValueEx(phkResult, lpValueName, 0%, dwType, lpData, Len6(lpData))

        ' Avaliar se a API retornou sucesso.
        ' Evaluate whether the API has returned success.
        If lngReturn <> 0 Then
            GoTo ErrorHandler
        End If

        ' Fechar a chave no banco de dados de registro do Windows.
        ' Close the key in the Windows registry database.
        RegCloseKey((phkResult))

        ' Retornar sucesso ao método.
        ' Return success to method.
        Return -1

ErrorHandler:

        ' Fechar a chave no banco de dados de registro do Windows.
        ' Close the key in the Windows registry database.
        RegCloseKey((phkResult))

        ' Retornar código de erro ao método.
        ' Return error code to method.
        Return 0

    End Function

End Class
